name: "Backup to Filecoin"
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0,8,16 * * *" # Every 8 hours.

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Backup to Filecoin
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Backup to Filecoin
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
        NFTSTORAGE_KEY: ${{ secrets.NFTSTORAGE_KEY }}
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
        REDIS_CONNECTION: ${{ secrets.REDIS_CONNECTION }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: node ./cron/backupFilecoin.js
