name: "Cache Trust Scores"
on:
  schedule:
    - cron: "0 0,12 * * *" # Every 12 hours.

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Trust Scores
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Cache Trust Scores
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
      run: node ./cron/cacheTrustScore.js

